# Generated by Django 3.2.9 on 2022-03-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_reviews_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
    ]
